/**
 * Bun-specific helpers for parsing HTTP `multipart/form-data` request bodies.
 *
 * This module adapts a Bun `Request` body and headers into the shared
 * `Multipart` model. Use `stream` from Bun HTTP handlers when form fields and
 * uploaded files should be consumed incrementally, for example validating text
 * fields while piping large file parts to storage. Use `persisted` when the
 * whole form should be collected into a record and file parts should be written
 * to scoped temporary files through the current `FileSystem`, `Path`, and
 * `Scope` services.
 *
 * Bun requests expose one-shot web streams, so choose one body reader and do
 * not call `formData`, `text`, `json`, or `arrayBuffer` before using this
 * module. Incoming `FormData` uploads must include a `multipart/form-data`
 * content type with the boundary generated by the client; when constructing
 * `FormData` requests, let the runtime set that header. Stream file content for
 * large uploads, reserve `contentEffect` for small files, and treat client
 * filenames as metadata rather than trusted filesystem paths. Persisted file
 * paths remain valid only for the surrounding scope.
 *
 * @since 4.0.0
 */
import type * as Effect from "effect/Effect"
import type { FileSystem } from "effect/FileSystem"
import type { Path } from "effect/Path"
import type * as Scope from "effect/Scope"
import * as Stream from "effect/Stream"
import * as Multipart from "effect/unstable/http/Multipart"
import * as BunStream from "./BunStream.ts"

/**
 * Parses a Bun `Request` body as multipart data and returns a stream of multipart parts.
 *
 * @category Constructors
 * @since 4.0.0
 */
export const stream = (source: Request): Stream.Stream<Multipart.Part, Multipart.MultipartError> =>
  BunStream.fromReadableStream({
    evaluate: () => source.body ?? emptyReadbleStream,
    onError: (cause) => Multipart.MultipartError.fromReason("InternalError", cause)
  }).pipe(
    Stream.pipeThroughChannel(Multipart.makeChannel(Object.fromEntries(source.headers)))
  )

const emptyReadbleStream = new ReadableStream({
  start(controller) {
    controller.enqueue(new Uint8Array())
    controller.close()
  }
})

/**
 * Parses and persists multipart data from a Bun `Request`, requiring file-system, path, and scope services.
 *
 * @category Constructors
 * @since 4.0.0
 */
export const persisted = (
  source: Request
): Effect.Effect<
  Multipart.Persisted,
  Multipart.MultipartError,
  | FileSystem
  | Path
  | Scope.Scope
> => Multipart.toPersisted(stream(source))
